#ifndef KEYBOARDBINDS_H
#define KEYBOARDBINDS_H

#include <linux/input.h>
#include <stdio.h>
#define MAX_LINE 100

struct MacroMap{
    const char *name;
    int value;
};

#define MY_MACRO_LIST \
    X(KEY_RESERVED) X(KEY_ESC) X(KEY_1) X(KEY_2) X(KEY_3) X(KEY_4) X(KEY_5) \
    X(KEY_6) X(KEY_7) X(KEY_8) X(KEY_9) X(KEY_0) X(KEY_MINUS) X(KEY_EQUAL) \
    X(KEY_BACKSPACE) X(KEY_TAB) X(KEY_Q) X(KEY_W) X(KEY_E) X(KEY_R) X(KEY_T) \
    X(KEY_Y) X(KEY_U) X(KEY_I) X(KEY_O) X(KEY_P) X(KEY_LEFTBRACE) X(KEY_RIGHTBRACE) \
    X(KEY_ENTER) X(KEY_LEFTCTRL) X(KEY_A) X(KEY_S) X(KEY_D) X(KEY_F) X(KEY_G) \
    X(KEY_H) X(KEY_J) X(KEY_K) X(KEY_L) X(KEY_SEMICOLON) X(KEY_APOSTROPHE) \
    X(KEY_GRAVE) X(KEY_LEFTSHIFT) X(KEY_BACKSLASH) X(KEY_Z) X(KEY_X) X(KEY_C) \
    X(KEY_V) X(KEY_B) X(KEY_N) X(KEY_M) X(KEY_COMMA) X(KEY_DOT) X(KEY_SLASH) \
    X(KEY_RIGHTSHIFT) X(KEY_KPASTERISK) X(KEY_LEFTALT) X(KEY_SPACE) X(KEY_CAPSLOCK) \
    X(KEY_F1) X(KEY_F2) X(KEY_F3) X(KEY_F4) X(KEY_F5) X(KEY_F6) X(KEY_F7) \
    X(KEY_F8) X(KEY_F9) X(KEY_F10) X(KEY_NUMLOCK) X(KEY_SCROLLLOCK) X(KEY_KP7) \
    X(KEY_KP8) X(KEY_KP9) X(KEY_KPMINUS) X(KEY_KP4) X(KEY_KP5) X(KEY_KP6) \
    X(KEY_KPPLUS) X(KEY_KP1) X(KEY_KP2) X(KEY_KP3) X(KEY_KP0) X(KEY_KPDOT) \
    X(KEY_ZENKAKUHANKAKU) X(KEY_102ND) X(KEY_F11) X(KEY_F12) X(KEY_RO) \
    X(KEY_KATAKANA) X(KEY_HIRAGANA) X(KEY_HENKAN) X(KEY_KATAKANAHIRAGANA) \
    X(KEY_MUHENKAN) X(KEY_KPJPCOMMA) X(KEY_KPENTER) X(KEY_RIGHTCTRL) X(KEY_KPSLASH) \
    X(KEY_SYSRQ) X(KEY_RIGHTALT) X(KEY_LINEFEED) X(KEY_HOME) X(KEY_UP) \
    X(KEY_PAGEUP) X(KEY_LEFT) X(KEY_RIGHT) X(KEY_END) X(KEY_DOWN) X(KEY_PAGEDOWN) \
    X(KEY_INSERT) X(KEY_DELETE) X(KEY_MACRO) X(KEY_MUTE) X(KEY_VOLUMEDOWN) \
    X(KEY_VOLUMEUP) X(KEY_POWER) X(KEY_KPEQUAL) X(KEY_KPPLUSMINUS) X(KEY_PAUSE) \
    X(KEY_SCALE) X(KEY_KPCOMMA) X(KEY_HANGEUL) X(KEY_HANJA) X(KEY_YEN) \
    X(KEY_LEFTMETA) X(KEY_RIGHTMETA) X(KEY_COMPOSE) X(KEY_STOP) X(KEY_AGAIN) \
    X(KEY_PROPS) X(KEY_UNDO) X(KEY_FRONT) X(KEY_COPY) X(KEY_OPEN) X(KEY_PASTE) \
    X(KEY_FIND) X(KEY_CUT) X(KEY_HELP) X(KEY_MENU) X(KEY_CALC) X(KEY_SETUP) \
    X(KEY_SLEEP) X(KEY_WAKEUP) X(KEY_FILE) X(KEY_SENDFILE) X(KEY_DELETEFILE) \
    X(KEY_XFER) X(KEY_PROG1) X(KEY_PROG2) X(KEY_WWW) X(KEY_MSDOS) X(KEY_COFFEE) \
    X(KEY_ROTATE_DISPLAY) X(KEY_CYCLEWINDOWS) X(KEY_MAIL) X(KEY_BOOKMARKS) \
    X(KEY_COMPUTER) X(KEY_BACK) X(KEY_FORWARD) X(KEY_CLOSECD) X(KEY_EJECTCD) \
    X(KEY_EJECTCLOSECD) X(KEY_NEXTSONG) X(KEY_PLAYPAUSE) X(KEY_PREVIOUSSONG) \
    X(KEY_STOPCD) X(KEY_RECORD) X(KEY_REWIND) X(KEY_PHONE) X(KEY_ISO) \
    X(KEY_CONFIG) X(KEY_HOMEPAGE) X(KEY_REFRESH) X(KEY_EXIT) X(KEY_MOVE) \
    X(KEY_EDIT) X(KEY_SCROLLUP) X(KEY_SCROLLDOWN) X(KEY_KPLEFTPAREN) \
    X(KEY_KPRIGHTPAREN) X(KEY_NEW) X(KEY_REDO) X(KEY_F13) X(KEY_F14) \
    X(KEY_F15) X(KEY_F16) X(KEY_F17) X(KEY_F18) X(KEY_F19) X(KEY_F20) \
    X(KEY_F21) X(KEY_F22) X(KEY_F23) X(KEY_F24) X(KEY_PLAYCD) X(KEY_PAUSECD) \
    X(KEY_PROG3) X(KEY_PROG4) X(KEY_ALL_APPLICATIONS) X(KEY_SUSPEND) X(KEY_CLOSE) \
    X(KEY_PLAY) X(KEY_FASTFORWARD) X(KEY_BASSBOOST) X(KEY_PRINT) X(KEY_HP) \
    X(KEY_CAMERA) X(KEY_SOUND) X(KEY_QUESTION) X(KEY_EMAIL) X(KEY_CHAT) \
    X(KEY_SEARCH) X(KEY_CONNECT) X(KEY_FINANCE) X(KEY_SPORT) X(KEY_SHOP) \
    X(KEY_ALTERASE) X(KEY_CANCEL) X(KEY_BRIGHTNESSDOWN) X(KEY_BRIGHTNESSUP) \
    X(KEY_MEDIA) X(KEY_SWITCHVIDEOMODE) X(KEY_KBDILLUMTOGGLE) X(KEY_KBDILLUMDOWN) \
    X(KEY_KBDILLUMUP) X(KEY_SEND) X(KEY_REPLY) X(KEY_FORWARDMAIL) X(KEY_SAVE) \
    X(KEY_DOCUMENTS) X(KEY_BATTERY) X(KEY_BLUETOOTH) X(KEY_WLAN) X(KEY_UWB) \
    X(KEY_UNKNOWN) X(KEY_VIDEO_NEXT) X(KEY_VIDEO_PREV) X(KEY_BRIGHTNESS_CYCLE) \
    X(KEY_BRIGHTNESS_AUTO) X(KEY_DISPLAY_OFF) X(KEY_WWAN) X(KEY_RFKILL) \
    X(KEY_MICMUTE)



struct KeyBind {
    int oldkey;
    int newkey;
};

void readConfFile(FILE *file, struct KeyBind *binds_array, size_t *barray_index);
void returnCode(struct input_event *ev,  struct KeyBind *binds_array, size_t barray_index);

#endif